fix: simple analyzer infos
parse-community/Parse-SDK-Flutter pull request #734
Opened 2022-04-30 23:45 UTC by fischerscode

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
This PR fixes the trivial, non breaking analyzer infos.

Related issue: #733 

### Approach
Mostly I just let the ide fix it.

### TODOs before merging
- [ ] Make sure the change to `_ParseLiveListElementWidgetState` did not break anything.

2022-04-30 23:47 UTC, fischerscode commented on packages/flutter/lib/src/utils/parse_live_list.dart
> -        vsync: this,
I'll have to test, if this really does not break the animation.

2022-04-30 23:49 UTC, fischerscode commented
Each `Prefer using lowerCamelCase for constant names.` info, might require a breaking change.

2022-05-02 10:18 UTC, fischerscode commented
> Merging [#734](https://codecov.io/gh/parse-community/Parse-SDK-Flutter/pull/734?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=parse-community) (https://github.com/parse-community/Parse-SDK-Flutter/commit/769e90081eefa164d063ceeda7c7b963f92f8d24) into [master](https://codecov.io/gh/parse-community/Parse-SDK-Flutter/commit/1280ce3bf24305aaf24e1d61f4ca792acfcad080?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=parse-community) (https://github.com/parse-community/Parse-SDK-Flutter/commit/1280ce3bf24305aaf24e1d61f4ca792acfcad080) will decrease coverage by 0.03%.

I think due to the introduction of `defaultParseFileConstructor`.

2022-05-02 16:22 UTC, mtrezza commented
Kindly request a review when this is ready for merge

2022-05-03 11:20 UTC, fischerscode commented
> I'll have to test, if this really does not break the animation.

Didn't test it yet. I'll request a review when I did.

2022-05-20 14:11 UTC, fischerscode commented
>  Make sure the change to _ParseLiveListElementWidgetState did not break anything.

It works as expected, but I'll revert the change since it would be breaking. Older versions of Flutter (before v2.2.0-10.1.pre) require `vsync`

2022-05-20 14:16 UTC, fischerscode commented on packages/flutter/lib/src/utils/parse_live_list.dart
> -        vsync: this,
It works, but I reverted it to avoid a breaking change when using older flutter versions.

2022-05-20 14:29 UTC, fischerscode commented
codecov should be fine. Might be due to more compact format or fewer imports.

2022-05-20 15:10 UTC, fischerscode commented
Sorry @phillwiggins pressed the wrong button.

2022-05-29 18:31 UTC, mtrezza requested changes
Could you please add the changelog entries to the corresponding packages?

Entries should only go to the package in which the changes occur. We do separate releases and versioning now. See https://github.com/parse-community/Parse-SDK-Flutter/issues/668#issuecomment-1140499834

If this PR does not fix a bug, add a feature or improve performance, but is merely a refactor to get rid of recommended code style changes, then this would not lead to a changelog entry. It would be merge as something like `refactor: fix analyzer code style warnings`.

2022-05-30 19:13 UTC, mtrezza requested changes

2022-05-30 19:13 UTC, mtrezza commented on packages/dart/CHANGELOG.md
> +### Refactoring
Could you move this to the top under a new version 3.1.1?
And rename the title to "Refactor".

2022-05-30 19:13 UTC, mtrezza commented on packages/flutter/CHANGELOG.md
> +### Refactoring
Could you move this to the top under a new version 3.1.2?
And rename the title to "Refactor".

2022-05-30 19:20 UTC, mtrezza approved these changes
Looks good! Let's try out this first dart - flutter combo release!

2022-05-30 19:21 UTC, merged

2022-05-30 19:24 UTC, mtrezza commented
Oops, we forgot forgot to bump the package versions. So no release this time :-) We'll just wait for the next PR, probably https://github.com/parse-community/Parse-SDK-Flutter/pull/738, and do a release.

2022-05-30 19:34 UTC, fischerscode commented
> Oops, we forgot forgot to bump the package versions.

Oops...

> Unless you feel like opening another PR just for the version bump.

If you want, I can do it. It might be best to test it soon rather then later.

2022-05-30 19:48 UTC, mtrezza commented
Sure, please go ahead

2022-05-30 19:55 UTC, fischerscode commented
> Sure, please go ahead

Link it to #733?