fix bug#774: null is not a subtype of String
parse-community/Parse-SDK-Flutter pull request #775
Opened 2022-07-09 09:14 UTC by Nidal-Bakir

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues/774).

### Issue Description
The response from `dio` error object could have a null `data` property

Related issue: #` no related issues`

### Approach
Add null aware operator `??`:
```
on dio.DioError catch (error) {
      return ParseNetworkByteResponse(
        data: error.response?.data ?? 'NetworkError',
        statusCode: error.response!.statusCode!,
      );
    }
```

### TODOs before merging
All set

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

2022-07-09 19:26 UTC, mtrezza commented
Could you please replace the PR title with `fix: <summary of what the issue is>`

2022-07-09 19:36 UTC, mtrezza requested changes
Could you add a test for this?

2022-07-10 13:10 UTC, Nidal-Bakir commented
Sure, but I can not find a way to mock the `_ParseDioClient` class to fack the DioError

2022-07-28 20:15 UTC, mtrezza commented
@parse-community/flutter-sdk-review what do you think, is this ready for merge?

2022-10-23 09:31 UTC, mtrezza commented
@Nidal-Bakir any particular reason for closing this?

2022-10-23 12:14 UTC, mtrezza commented
@parse-community/flutter-sdk-review should this PR be merged?

2022-10-24 01:21 UTC, Nidal-Bakir commented
@mtrezza 
I'm sorry, I did not mean to close the PR! 
I did not know that if I deleted the forked repository from my account all my PR would be closed.

2022-10-24 11:45 UTC, mtrezza commented
I've reopened, thanks for clarifying

2022-11-29 05:58 UTC, mbfakourii commented on packages/dart/lib/src/network/parse_dio_client.dart
> +        statusCode: error.response!.statusCode!,
I ran this code without internet connection and got null error in statusCode!
I suggest you change the code like this

```
return ParseNetworkResponse(
  data: error.response?.data ?? _fallbackErrorData,
  statusCode: error.response?.statusCode! ?? -1,
);
```

2023-02-24 19:31 UTC, Nidal-Bakir commented
Reopening in a different PR because I lost all the progress and the reference of these changes [here](https://github.com/parse-community/Parse-SDK-Flutter/pull/825)

2023-02-24 19:31 UTC, closed without merging