feat: Add query constraint `wherePolygonContains` to determine whether a point in within a polygon
parse-community/Parse-SDK-Flutter pull request #778
Opened 2022-07-18 17:27 UTC by Paul0Cesar

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
Create a new constraint to check if Polygon contains the geopoint

Closes: #777 

### Approach

create a new method to add polygon constraint in query

### TODOs before merging
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2022-07-20 11:47 UTC, mtrezza commented
Could you add a test?

2022-08-18 19:14 UTC, mtrezza commented on packages/dart/test/parse_query_test.dart
> +      expect(parseObject.containsKey("geometry"), true);
```suggestion
      ParseResponse response = await queryBuilder.query();
      expect(response.results?.first, isA<ParseObject>());
      ParseObject parseObject = response.results?.first;
      expect(parseObject.objectId, "eT9muOxBTK");
      expect(parseObject.containsKey("geometry"), true);
```

2022-08-18 19:14 UTC, mtrezza commented on packages/dart/test/parse_query_test.dart
> +      expect(result.path, '/classes/TEST_SCHEMA');
```suggestion
      )).captured.single);
      expect(result.path, '/classes/TEST_SCHEMA');
```

2022-08-18 19:18 UTC, mtrezza requested changes
Could you take a look at the failing lint test?

2022-09-05 13:30 UTC, Paul0Cesar commented
> Could you take a look at the failing lint test?

@mtrezza , sorry for the late answer, I fix the lint error

2022-09-09 17:34 UTC, mtrezza commented
Thanks @Paul0Cesar, all tests pass. Let's wait for a review by @parse-community/flutter-sdk-review to merge this.

2022-11-28 13:43 UTC, mbfakourii submitted a review, later dismissed

2022-11-28 23:11 UTC, mtrezza commented
@Paul0Cesar To merge this, could you add the change log entry and bump the version by a minor version number? It seems this is only related to the dart package, so the change log and version number only needs to be changed there.

2023-01-18 23:54 UTC, Paul0Cesar commented
@mtrezza , sorry for the late answer, I merge the master branch, fix the constant SINGLE QUERY not using _SINGLE_QUERY, and change the version

2023-01-19 06:06 UTC, mbfakourii requested changes
The test must be changed

2023-01-19 13:46 UTC, Paul0Cesar commented
@mbfakourii, I change the code formatting, can you check again?

2023-01-19 13:51 UTC, mbfakourii submitted a review, later dismissed
Thanks for the changes looks good

2023-01-20 15:25 UTC, mtrezza submitted a review, later dismissed
Minor changelog

2023-01-20 15:25 UTC, mtrezza commented on packages/dart/CHANGELOG.md
> +* Additional query constraint:`wherePolygonContains`([#777](https://github.com/parse-community/Parse-SDK-Flutter/issues/777))
```suggestion
* Add query constraint `wherePolygonContains` to determine whether a point in within a polygon ([#777](https://github.com/parse-community/Parse-SDK-Flutter/issues/777))
```

2023-01-20 15:25 UTC, mtrezza commented on packages/dart/CHANGELOG.md
> +## [3.1.11](https://github.com/parse-community/Parse-SDK-Flutter/compare/dart-3.1.10...dart-3.1.11) (2023-01-18)
```suggestion
## [3.1.11](https://github.com/parse-community/Parse-SDK-Flutter/compare/dart-3.1.10...dart-3.1.11) (2023-01-20)
```

2023-01-20 15:29 UTC, mtrezza requested changes
Lint fails, could you take a look?

2023-01-21 15:47 UTC, Paul0Cesar commented
@mtrezza , done, can you check:?  :rocket:

2023-01-21 22:17 UTC, mtrezza requested changes

2023-01-21 22:17 UTC, mtrezza commented on packages/dart/test/parse_query_test.dart
> +      expect(result.query, expectedQuery.query);
```suggestion
      expect(response.results?.first, isA<ParseObject>());
      expect(parseObject.objectId, "eT9muOxBTK");
      expect(parseObject.containsKey("geometry"), true);
      expect(result.path, '/classes/TEST_SCHEMA');
      expect(result.query, expectedQuery.query);
```

2023-01-21 22:17 UTC, mtrezza commented on packages/dart/test/parse_query_test.dart
> +      ParseObject parseObject = response.results?.first;
```suggestion
      ParseResponse response = await queryBuilder.query();
      ParseObject parseObject = response.results?.first;
```

2023-01-21 22:35 UTC, mtrezza commented on packages/dart/CHANGELOG.md
> +## [3.1.11](https://github.com/parse-community/Parse-SDK-Flutter/compare/dart-3.1.10...dart-3.1.11) (2023-01-20)
```suggestion
## [3.1.11](https://github.com/parse-community/Parse-SDK-Flutter/compare/dart-3.1.10...dart-3.1.11) (2023-01-21)
```

2023-01-21 22:36 UTC, mtrezza approved these changes
Looks good

2023-01-21 22:36 UTC, merged