fix: full value in list and map in parseEncode
parse-community/Parse-SDK-Flutter pull request #789
Opened 2022-09-16 14:26 UTC by mbfakourii

### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
Solve the parseEncode problem in list and map

Related issue: https://github.com/parse-community/Parse-SDK-Flutter/issues/788

### Approach
The ```full: full``` was added for when we use the list and map in parseEncode and toJson

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

2022-09-16 18:46 UTC, mtrezza commented
Could you please rephrase the PR title? It will become the changelog entry and a developer should be able to understand what this fixes without reading the PR.

2022-10-27 00:13 UTC, mtrezza requested changes
Could you add a test to demonstrate what is not working correctly?

2022-10-27 00:13 UTC, mtrezza commented on packages/dart/lib/src/utils/parse_encoder.dart
> +      return parseEncode(value, full: full);
```suggestion
      return parseEncode(value, full);
```

2022-10-27 00:13 UTC, mtrezza commented on packages/dart/lib/src/utils/parse_encoder.dart
> +      value[k] = parseEncode(v, full: full);
```suggestion
      value[k] = parseEncode(v, full);
```

2022-10-27 07:46 UTC, mbfakourii commented
> Could you add a test to demonstrate what is not working correctly?

Test added

2022-10-27 22:44 UTC, mtrezza commented on packages/dart/lib/src/utils/parse_encoder.dart
> +      return parseEncode(value, full);
Apologies, I was thinking in the wrong programming language

2022-10-27 22:47 UTC, mtrezza commented on packages/dart/lib/src/utils/parse_encoder.dart
> +      return parseEncode(value, full);
```suggestion
      return parseEncode(value, full: full);
```

2022-10-27 22:47 UTC, mtrezza commented on packages/dart/lib/src/utils/parse_encoder.dart
> +      value[k] = parseEncode(v, full);
```suggestion
      value[k] = parseEncode(v, full: full);
```

2022-10-27 22:48 UTC, mtrezza reviewed
There's still a lint issue, not sure what it is, because the logs don't show any specific message. Do you have any idea?

2022-10-28 06:17 UTC, mbfakourii commented
> There's still a lint issue, not sure what it is, because the logs don't show any specific message. Do you have any idea?

It is for Dart code format
I made a commit, it is probably fixed

2022-10-29 15:56 UTC, mtrezza commented
Indeed, the tests pass, now we just need a review from @parse-community/flutter-sdk-review

2022-11-11 21:34 UTC, mtrezza commented
There has been no additional review, but I'll go ahead and merge it anyway; if there is an issue, we'll find out.

2022-11-15 13:29 UTC, mtrezza approved these changes
Looks good!

2022-11-15 14:07 UTC, merged