add "and" and "nor" in QueryBuilder
parse-community/Parse-SDK-Flutter pull request #795
Opened 2022-10-18 07:54 UTC by mbfakourii

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
add ```and``` and ```nor```
add ```_constructorInitialize``` function for handle ```and``` , ```nor``` and ```or``` in QueryBuilder

### Approach
The value of ```and``` and ```nor```  was not present in this package

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

2022-10-19 08:09 UTC, mtrezza requested changes
Could you add tests? There is also a lint issue.

2022-10-27 10:03 UTC, mbfakourii commented
> Could you add tests? There is also a lint issue.

I added three tests for and, nor, or

2022-10-27 22:41 UTC, mtrezza commented
I don't think you need to add anything to README, what would you add?

2022-10-28 06:07 UTC, mbfakourii commented
> I don't think you need to add anything to README, what would you add?

documentation for how to use and and nor

2022-10-29 16:11 UTC, mtrezza commented
Oh, if that's not there yet, it would be great if you could add it!

2022-11-13 20:43 UTC, mtrezza commented on packages/dart/README.md
> +and also if you want to find objects that match several queries you can use __QueryBuilder.and__  and If you want to find objects that do not match all queries, you can use __QueryBuilder.nor__
```suggestion

To find objects that match several queries use __QueryBuilder.and__ . To find objects that do not match any given query use __QueryBuilder.nor__.
```

2022-11-13 20:44 UTC, mtrezza commented on packages/flutter/README.md
> +and also if you want to find objects that match several queries you can use __QueryBuilder.and__  and If you want to find objects that do not match all queries, you can use __QueryBuilder.nor__
```suggestion

To find objects that match several queries use __QueryBuilder.and__. To find objects that do not match any given query use __QueryBuilder.nor__.
```

2022-12-19 04:49 UTC, mbfakourii commented
I use ```and``` in a project that is used by several people every day. It seems that there is no problem

2022-12-21 13:49 UTC, mtrezza commented
Rerunning failed tests

2022-12-21 14:20 UTC, mbfakourii commented
> Rerunning failed tests

What is the problem, like all the tests are passed

2022-12-21 14:41 UTC, mtrezza commented
Now they did, earlier they did not, probably some flaky tests.

2022-12-21 14:42 UTC, mtrezza commented
Could you again bump the versions and add the changelog entry?

2022-12-21 15:13 UTC, mtrezza commented on packages/dart/CHANGELOG.md
> +* Add and, nor operators in QueryBuilder ([#795](https://github.com/parse-community/Parse-SDK-Flutter/issues/795))
```suggestion
* Add `and`, `nor` operators in QueryBuilder ([#795](https://github.com/parse-community/Parse-SDK-Flutter/issues/795))
```

2022-12-21 15:14 UTC, mtrezza approved these changes

2022-12-21 15:20 UTC, merged