fix: dio error holds a reference to null values
parse-community/Parse-SDK-Flutter pull request #825
Opened 2023-02-24 19:27 UTC by Nidal-Bakir

When an error occurs, the Dio error object could hold null properties  causing the error (Type 'Null' is not a subtype of type 'Object')

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

Closes: [774](https://github.com/parse-community/Parse-SDK-Flutter/issues/774)

### Approach
Add null aware operator `??`:
``` dart
on dio.DioError catch (error) {
      return ParseNetworkResponse(
        data: error.response?.data ?? _fallbackErrorData,
        statusCode: error.response?.statusCode ?? ParseError.otherCause,
      );
    }
```

### TODOs before merging
All set

- [] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [] A changelog entry

2023-02-25 07:03 UTC, mbfakourii approved these changes
Thanks for checking nulls, looks good

2023-02-25 10:36 UTC, mtrezza approved these changes

2023-02-25 10:37 UTC, mtrezza requested changes
Could you add a changelog entry using the PR title and bump the version? See existing entries for examples.

2023-02-26 12:09 UTC, mtrezza approved these changes
Looks good!

2023-02-26 12:23 UTC, merged