fix: Downgrade the collection dependency to 1.16.0
parse-community/Parse-SDK-Flutter pull request #880
Opened 2023-05-13 23:40 UTC by Nidal-Bakir

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

Closes: FILL_THIS_OUT

### Approach

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

2023-05-13 23:43 UTC, Nidal-Bakir commented
I will test here also.
I will upgrade the Parse SDK version in the Flutter package to ^5.0.0 to see if everything is good and then revert back

2023-05-13 23:52 UTC, Nidal-Bakir commented
OMG, I forgot that Flutter SDK will get the Dart SDK from pub. I really need to sleep....  o-O

2023-05-13 23:56 UTC, mtrezza commented
Yes, we just need to add the changelog entry.

Since this is lowering the collection dependency it seems more of a `feat` (more compatibility) than `fix`.

2023-05-13 23:58 UTC, mtrezza commented
Oh why is the CI now passing? Don't we have to make a Dart release first?

2023-05-14 00:00 UTC, Nidal-Bakir commented
because the Dart SDK 4.0.0 do not depend on collection 1.17.1

2023-05-14 00:06 UTC, mtrezza commented
Oh right, this is confusing, could you add the changelog entry, then we can merge this, I'll make a release and we should be able to merge https://github.com/parse-community/Parse-SDK-Flutter/pull/868.

2023-05-14 00:07 UTC, Nidal-Bakir commented
sure

2023-05-14 00:11 UTC, Nidal-Bakir commented
or should it be 5.1.0?

2023-05-14 00:28 UTC, mtrezza commented
Yes

2023-05-14 00:29 UTC, mtrezza requested changes

2023-05-14 00:29 UTC, mtrezza commented on packages/dart/CHANGELOG.md
> +* feat: Downgrade collection dependency to ^1.16.0 for compatibility with Flutter >=3.3 ([#880](https://github.com/parse-community/Parse-SDK-Flutter/pull/880))
```suggestion
## [5.1.0](https://github.com/parse-community/Parse-SDK-Flutter/compare/dart-5.0.0...dart-5.1.0) (2023-05-14)

### Features

* Downgrade collection dependency to ^1.16.0 for compatibility with Flutter >=3.3 ([#880](https://github.com/parse-community/Parse-SDK-Flutter/pull/880))
```

2023-05-14 00:30 UTC, mtrezza requested changes

2023-05-14 00:30 UTC, mtrezza commented on packages/dart/lib/src/base/parse_constants.dart
> +const String keySdkVersion = '5.0.1';
```suggestion
const String keySdkVersion = '5.1.0';
```

2023-05-14 00:30 UTC, mtrezza commented on packages/dart/pubspec.yaml
> +version: 5.0.1
```suggestion
version: 5.1.0
```

2023-05-14 00:31 UTC, mtrezza approved these changes
Looks good, waiting for CI to pass...

2023-05-14 00:37 UTC, merged