refactor: Update package_info_plus
parse-community/Parse-SDK-Flutter pull request #934
Opened 2023-06-07 16:22 UTC by mbfakourii

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue

Closes: #821

## Approach
Update package_info_plus to ```package_info_plus: ^4.0.2```

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

2023-06-07 19:46 UTC, mtrezza requested changes
CI tests failing...

2023-06-08 11:52 UTC, mtrezza commented
Re-running CI to get all tests to pass

2023-06-08 18:27 UTC, mbfakourii commented
> It seems that the CI is always failing, and it's not just the coverage upload. Could you take a look?

Yes, Sure

2023-06-09 13:46 UTC, mbfakourii commented
The last error related to the [code format](https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/5222554583/jobs/9428184149) is not a problem in my system, but it is a problem in CI!

![image](https://github.com/parse-community/Parse-SDK-Flutter/assets/20955005/8bfcbf29-5cdc-4024-b549-409802f0c74c)

2023-06-09 15:21 UTC, mtrezza commented
I think the issue is that the linter is part of the dart framework. So if the Dart beta version enforces a new lint rule, the lint check for that framework version will fail. That's why it's only failing for "Dart beta".

2023-06-09 20:11 UTC, mbfakourii commented
@mtrezza 
Why should the beta version be checked?

2023-06-10 10:30 UTC, mtrezza commented
It fails `dart format`, which I assume is because the linter changed in that dart version.

2023-06-10 14:15 UTC, mtrezza commented on .github/workflows/ci.yml
> -          - name: Dart beta
Why removed?

2023-06-10 14:15 UTC, mbfakourii commented
Beta removed from ci

2023-06-10 14:16 UTC, mtrezza commented
Why removed?

2023-06-10 14:20 UTC, mbfakourii commented
> Why removed? Adding beta was debated thoroughly in a previous PR and we deiced to add it. If we now remove it we should find arguments that outweigh the other arguments.
> 
> I think we'd need to:
> 
> 1. Find out what exactly the linter is complaining about.
> 2. If we can't fix it, remove linting for beta, instead of removing beta altogether.
> 3. If we can't removing linting for beta, decide whether we should remove beta.

I was testing and returned it

2023-06-10 14:21 UTC, mtrezza commented
Do you think you could run `dart format` locally with a beta version to find out what the 1 issue is the linter corrects?

2023-06-10 14:22 UTC, mbfakourii commented
> Do you think you could run `dart format` locally with the dart beta version to find out what the 1 issue is the linter corrects?

I will test

2023-06-10 16:35 UTC, mbfakourii commented
@mtrezza 
It has problems from version 2.18 to 3. I will roll back to the previous version. I think it is better if there is a problem in the beta!

2023-06-10 16:36 UTC, mtrezza commented
Is there no way we can slightly refactor the code so it passes both?

2023-06-10 16:37 UTC, mbfakourii commented
> Is there no way we can slightly refactor the code so it passes both?

I will check

2023-06-10 18:30 UTC, mbfakourii commented
fixed

2023-06-10 19:14 UTC, mtrezza approved these changes
Well done! So we can keep the beat versions in the CI; is this ready for merge?

2023-06-10 19:21 UTC, mbfakourii commented
> Well done! So we can keep the beat versions in the CI; is this ready for merge?

Yes, it is ready to merge

2023-06-10 19:55 UTC, merged