fix: Changing `awesome_notifications` package to `flutter_local_notifications` in `ParseNotification`
parse-community/Parse-SDK-Flutter pull request #940
Opened 2023-06-21 09:47 UTC by mbfakourii

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue
Changing `awesome_notifications` package to `flutter_local_notifications` in `ParseNotification`

Closes: #936

## Approach
n/a

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

2023-06-21 10:45 UTC, mtrezza requested changes
Requires clarification of https://github.com/parse-community/Parse-SDK-Flutter/issues/936#issuecomment-1600600707

2023-06-28 13:31 UTC, mbfakourii commented
@mtrezza 
Ready to merge?

2023-06-28 13:33 UTC, mtrezza commented
Is this package change in any way a breaking change for developers, or is that only internally?

2023-06-28 13:34 UTC, mbfakourii commented
> Is this package change in any way a breaking change for developers, or is that only internally?

No, it is not a breaking, only internally

2023-06-28 13:57 UTC, mtrezza commented
Got it, then this would be a `refactor`, but that doesn't create a changelog entry and won't publish a release. Should we make a release and publish this as a `feat`?

2023-06-28 18:58 UTC, mtrezza requested changes

2023-06-28 18:58 UTC, mtrezza commented on packages/flutter/CHANGELOG.md
> +* Changing `awesome_notifications` package to `flutter_local_notifications` in `ParseNotification` ([#940](https://github.com/parse-community/Parse-SDK-Flutter/pull/940))
```suggestion
## [5.1.1](https://github.com/parse-community/Parse-SDK-Flutter/compare/flutter-5.1.0...flutter-5.1.1) (2023-06-28)

### Bug Fixes

* Push notifications in iOS not working; this changes the dependency in `ParseNotification` from `awesome_notifications` to `flutter_local_notifications` ([#940](https://github.com/parse-community/Parse-SDK-Flutter/pull/940))
```

2023-06-28 19:01 UTC, mtrezza approved these changes

2023-06-28 19:01 UTC, merged